In [7]:
import numpy as np
arr=np.array([1,2,3])
arr2=np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr2)




[1 2 3]
[[1 2 3]
 [4 5 6]]


In [13]:
np.zeros((3,3)) # 3x3 array of zeros
np.ones((4,2)) # 4x2 array of one
np.full((3,4),6) # 3x4 array of 6

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [14]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

print("Shape:", arr.shape)   # (2, 3) → 2 rows, 3 columns
print("Size:", arr.size)     # 6 → total elements
print("Dimensions:", arr.ndim) # 2 → 2D array
print("Data type:", arr.dtype) # int64 (or int32 on Windows)

Shape: (2, 3)
Size: 6
Dimensions: 2
Data type: int64


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)
# [[1 2]
#  [3 4]
#  [5 6]]

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]