In [4]:
import numpy as np 
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [6]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [8]:
flat=arr.flatten()

In [9]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [10]:
flat[0]

np.int64(1)

In [12]:
flat[3]

np.int64(4)

In [13]:
flat[3:6]

array([4, 5, 6])

In [14]:
flat[:5] # same as flat[0:5]

array([1, 2, 3, 4, 5])

In [15]:
flat[::2] # every 2 elemt
b=flat[4:7]
b[0]=1234 #index 4 (5th element 0 of flat is also changed
b
c=b.copy # or c=flat[4:7] is a copy 


array([1234,    6,    7])

In [16]:
flat 

array([   1,    2,    3,    4, 1234,    6,    7,    8,    9,   10,   11,
         12])

In [22]:
arr2=np.array([1,54,28,65,2,3,84,0,0,-5,4,7])
 arr2[[2,1,3]] # elemnt at index 2 1 3
arr2[arr2>3]    # element greater the 3


array([54, 28, 65, 84,  4,  7])